### ISSUE TITLE
ganivut: No such file or directory: './results/primitives/mymodel/synthesis/imitations/mymodel-myoutput.mp4'

### ISSUE THREAD

**Issue by ant-base** [eyaler/avatars4all#2]
The error is happening on Google Colab.
Whether I run it with the default videos and images or with mine, whether I trim the video, the error is always the same.

At the Animate stage:
No such file or directory: './results/primitives/mymodel/synthesis/imitations/mymodel-myoutput.mp4'

<img width="1604" alt="Screenshot 2022-10-28 at 14 02 34" src="https://user-images.githubusercontent.com/116880129/198582535-3b91a742-d0d2-4090-8d9d-0228158ba608.png">

**Comment by eyaler** [comment]
@ant-base this was due to (1) google breaking colab again by removing cuda 10.1 and (2) checkpoint URL has changed.
It works now and code is updated to upstream, however note that iPERCore added new capabilities in 0.2.0 which i did not add yet

**Comment by eyaler** [comment]
i further moved to cuda 11.1 to allow compatibility with A100

**Comment by eyaler** [comment]
btw. I coundn't figure out how to install cudnn...
