### ISSUE TITLE
Inquiry About Wav2Skit Colab Notebook Availability

### ISSUE THREAD

**Issue by solt152152** [eyaler/avatars4all#4]
Hello Eyal Gruss and the avatars4all team,

I hope this message finds you well. I've been exploring the avatars4all repository with great interest, particularly the feature that combines Wav2Lip with speaker diarization for automatic animated skit creation ("Wav2Skit").

I noticed the feature mentioned in the repository's README, but I could not locate the Colab notebook that corresponds to this functionality. Could you please guide me on how I might access the Wav2Skit notebook, or if there are plans to make it available in the future?

Thank you for your assistance and the incredible work on this project.

Best regards,
Yohei

**Comment by eyaler** [comment]
@solt152152 
sorry for late reply. it's in the wav2lip notebook, just mark "switch_speakers" and upload more than 1 image.
the models were broken for some time now due to breaking changes in the libs - but i now pushed a fix.
